dataset:
  dataset_dir: 'datasets/preprocessed'
model:
  name: 'lenet'
train:
  device: 'cuda'
  batch_size: 32
  optimizer: 'sgd'
  base_lr: 0.01
  momentum: 0.9
  nesterov: True
  weight_decay: 0.0001
  seed: 0
  test_id: 0
  val_ratio: 0.1
  outdir: 'results/lenet/exp00'
  log_period: 100
  checkpoint_period: 10
  use_tensorboard: True
  train_dataloader:
    num_workers: 2
    drop_last: True
    pin_memory: False
  val_dataloader:
    num_workers: 1
    pin_memory: False
scheduler:
  epochs: 40
  type: 'multistep'
  milestones: [30, 35]
  lr_decay: 0.1
  lr_min_factor: 0.001
test:
  checkpoint: ''
  outdir: ''
  device: 'cuda'
  batch_size: 256
  dataloader:
    num_workers: 1
    pin_memory: False
cudnn:
  benchmark: True
  deterministic: False