dataset:
  dataset_dir: datasets/preprocessed
model:
  name: resnet_preact
test:
  checkpoint: experiments/resnet_preact/exp00/00/checkpoint_0040.pth
  output_dir: experiments/resnet_preact/exp00/00/eval
  device: cuda
  batch_size: 256
  dataloader:
    num_workers: 1
    pin_memory: False
cudnn:
  benchmark: True
  deterministic: False